global:
  envs:
    PING_IDENTITY_ACCEPT_EULA: "YES"
  
  ingress:
    enabled: true
    addReleaseNameToHost: append
    defaultDomain: ping-devops.com
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    spec:
      ingressClassName: nginx-public

#############################################################
# pingfederate-admin values
#############################################################
pingfederate-admin:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/samir-gandhi/gitops-lab-platform.git
    SERVER_PROFILE_PATH: server-profiles/pingfederate

  ingress:
    enabled: true
  
  container:
    resources:
      requests:
        cpu: 1
        memory: 3Gi
      limits:
        cpu: 2
        memory: 5Gi
    waitFor:
      pingdirectory:
        service: ldaps

#############################################################
# pingfederate-engine values
#############################################################
pingfederate-engine:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/samir-gandhi/gitops-lab-platform.git
    SERVER_PROFILE_PATH: server-profiles/pingfederate
  container:
    replicaCount: 1
    waitFor:
      pingfederate-admin:
        service: https

    # resources:
    #   requests:
    #     cpu: 1
    #     memory: 3Gi
    #   limits:
    #     cpu: 2
    #     memory: 5Gi

pingdirectory:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/samir-gandhi/gitops-lab-platform.git
    SERVER_PROFILE_PATH: server-profiles/pingdirectory

  persistentvolume:
    enabled: true
    volumes:
      - name: out-dir
        mountPath: /opt/out
        storage: 8Gi

pingdataconsole:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/samir-gandhi/gitops-lab-platform.git
    SERVER_PROFILE_PATH: server-profiles/pingdirectory