name: Infra Deploy
on: 
  create:
    paths:
      - 01-infrastructure/**/*
      - server-profiles/**/*
      - .github/workflows/push_infra.yml
      - .github/workflows/drift_check.yml
  push:
    paths:
      - 01-infrastructure/**/*
      - server-profiles/**/*
      - .github/workflows/push_infra.yml
      - .github/workflows/drift_check.yml

jobs:
  fmt:
    runs-on: ubuntu-latest
    env:
      TERRAFORM_ENV_BASE64: ${{ secrets.TERRAFORM_ENV_BASE64 }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: hashicorp/setup-terraform@v3
    - name: fmt-check
      run: |
        terraform fmt -recursive -check .

  lint:
    needs: [fmt]
    runs-on: ubuntu-latest
    env:
      TERRAFORM_ENV_BASE64: ${{ secrets.TERRAFORM_ENV_BASE64 }}
    steps:
    - uses: actions/checkout@v4
    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        tflint_version: latest

    - name: tflint
      run: |
        echo "***Running terraform lint***"
        tflint --recursive

  validate:
    needs: [lint]
    name: validate
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TERRAFORM_ENV_BASE64: ${{ secrets.TERRAFORM_ENV_BASE64 }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    - name: Terraform Validate
      run: |-
        echo $TERRAFORM_ENV_BASE64 | base64 -d > tfvars
        source tfvars
        _tfdir=01-infrastructure
        _branch=$(echo "${GITHUB_REF}" | sed -e "s#refs/heads/##g")
        
        export TF_VAR_k8s_helm_deployment_name="${_branch}"
        export TF_VAR_pingone_environment_name=${_branch}
        case $_branch in
          prod)
            _stateKey="${TF_VAR_tf_state_key_prefix_infrastructure}/prod/terraform.tfstate"
            ;;
          qa)
            _stateKey="${TF_VAR_tf_state_key_prefix_infrastructure}/qa/terraform.tfstate"
            ;;
          *)
            _stateKey="${TF_VAR_tf_state_key_prefix_infrastructure}/dev/${_branch}/terraform.tfstate"
            ;;
        esac
        terraform -chdir=${_tfdir} init \
          -backend-config="bucket=$TF_VAR_tf_state_bucket" \
          -backend-config="region=$TF_VAR_tf_state_region" \
          -backend-config="key=${_stateKey}"
        echo "***Running terraform validate***"
        terraform -chdir=${_tfdir} validate
        
  deploy:
    if: ${{ !contains(github.event.commits[0].message, '[skip ci]')}}
    name: Deploy
    needs: [validate]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TERRAFORM_ENV_BASE64: ${{ secrets.TERRAFORM_ENV_BASE64 }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Configure AWS Credentials
      run: |
        echo $TERRAFORM_ENV_BASE64 | base64 -d > tfvars
        source tfvars
        aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
        aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
        aws configure set region ${AWS_REGION}
    - name: Create state file (in-progress)
      run: |
        # Status can be in-progress, ready, or failed
        BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
        EPOCH_TIME=$(date +%s)
        echo "{\"branch\":\"$BRANCH_NAME\", \"infraStatus\":\"in-progress\", \"epoch\":$EPOCH_TIME}" > infra_status.json
        echo $TERRAFORM_ENV_BASE64 | base64 -d > tfvars
        source tfvars
        _aws_bucket="${TF_VAR_tf_state_bucket}"
        aws s3 cp infra_status.json "s3://${_aws_bucket}/branch_infra_status/${BRANCH_NAME}/infra_status.json"

    - uses: hashicorp/setup-terraform@v3
    - name: Terraform Apply
      run: |-
        mkdir -p ${HOME}/.kube
        echo "${{ secrets.KUBECONFIG_YAML }}" | base64 --decode > ${HOME}/.kube/config
        kubectl version
        echo $TERRAFORM_ENV_BASE64 | base64 -d > tfvars
        source tfvars
        _aws_bucket="${TF_VAR_tf_state_bucket}"
        _tfdir="01-infrastructure"
        _branch=$(echo "${GITHUB_REF}" | sed -e "s#refs/heads/##g")
        export TF_VAR_k8s_helm_deployment_name="${_branch}"
        export TF_VAR_pingone_environment_name="${_branch}"
        case $_branch in
          prod)
            _stateKey="${TF_VAR_tf_state_key_prefix_infrastructure}/prod/terraform.tfstate"
            ;;
          qa)
            _stateKey="${TF_VAR_tf_state_key_prefix_infrastructure}/qa/terraform.tfstate"
            ;;
          *)
            _stateKey="${TF_VAR_tf_state_key_prefix_infrastructure}/dev/${_branch}/terraform.tfstate"
            ;;
        esac
        terraform -chdir=${_tfdir} init \
          -backend-config="bucket=$TF_VAR_tf_state_bucket" \
          -backend-config="region=$TF_VAR_tf_state_region" \
          -backend-config="key=${_stateKey}"
        echo "***Running terraform apply***"
        terraform -chdir=${_tfdir} apply --auto-approve
        if [ $? -ne 0 ]; then
          echo "Terraform apply failed, updating infra status to 'failed'"
          echo "{\"branch\":\"${_branch}\", \"infraStatus\":\"failed\", \"epoch\":$EPOCH_TIME}" > infra_status.json
          aws s3 cp infra_status.json "s3://${_aws_bucket}/branch_infra_status/${_branch}/infra_status.json"
          exit 1
        else
          echo "Terraform apply succeeded, updating infra status to 'ready'"
          echo "{\"branch\":\"${_branch}\", \"infraStatus\":\"ready\", \"epoch\":$EPOCH_TIME}" > infra_status.json
          aws s3 cp infra_status.json "s3://${_aws_bucket}/branch_infra_status/${_branch}/infra_status.json"
        fi